import * as Collapsible from "@radix-ui/react-collapsible";
import { ChevronDown, FolderOpen } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import type { BatchResult } from "@/types/domain";

export function CompletionDialog({ result, onDone, onOpenOutput }: { result: BatchResult; onDone: () => void; onOpenOutput: () => void }) {
  const { t } = useTranslation();
  const failedItems = result.items.filter((item) => item.errorCode);
  const [detailsOpen, setDetailsOpen] = useState(false);
  return <Dialog open onOpenChange={(open) => { if (!open) onDone(); }}><DialogContent aria-describedby="completion-description"><DialogTitle className="text-lg font-semibold">{t(result.cancelled ? "completion.cancelledTitle" : "completion.title")}</DialogTitle><p id="completion-description" className="mt-1 text-sm text-slate-600">{t("completion.summary")}</p><dl className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-lg bg-emerald-50 p-3"><dt className="text-xs text-slate-600">{t("completion.succeeded")}</dt><dd className="mt-1 text-xl font-semibold text-emerald-800">{result.succeeded}</dd></div><div className="rounded-lg bg-red-50 p-3"><dt className="text-xs text-slate-600">{t("completion.failed")}</dt><dd className="mt-1 text-xl font-semibold text-red-800">{result.failed}</dd></div><div className="rounded-lg bg-slate-100 p-3"><dt className="text-xs text-slate-600">{t("completion.skipped")}</dt><dd className="mt-1 text-xl font-semibold">{result.skipped}</dd></div></dl><div className="mt-5 rounded-lg border border-slate-200 p-3"><p className="text-xs text-slate-600">{t("completion.outputDirectory")}</p><p className="mt-1 truncate text-sm font-medium">{result.outputDirectory}</p></div>{failedItems.length > 0 && <Collapsible.Root open={detailsOpen} onOpenChange={setDetailsOpen} className="mt-4"><Collapsible.Trigger asChild><Button type="button" variant="ghost" className="w-full justify-between border border-red-200 text-red-800">{t("completion.failedItems", { count: failedItems.length })}<ChevronDown className={detailsOpen ? "size-4 rotate-180" : "size-4"} /></Button></Collapsible.Trigger><Collapsible.Content className="mt-2 max-h-32 overflow-auto rounded-lg border border-red-100"><ul className="divide-y divide-red-100">{failedItems.map((item) => <li key={`${item.inputPath}-${item.itemIndex}`} className="px-3 py-2"><p className="truncate text-sm">{item.inputPath}</p><p className="mt-1 font-mono text-xs text-red-700">{item.errorCode}</p></li>)}</ul></Collapsible.Content></Collapsible.Root>}<div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button type="button" variant="outline" className="w-full sm:w-auto" disabled={!result.outputDirectory} onClick={onOpenOutput}><FolderOpen className="size-4" />{t("completion.openOutput")}</Button><Button type="button" className="w-full sm:w-auto" onClick={onDone}>{t("action.done")}</Button></div></DialogContent></Dialog>;
}
